services:

  # fitbit-data-replicator:
  #   build: .
  #   environment:
  #     APP_PORT: 9199

  influxdb:
    image: influxdb:2.7.6
    ports:
      - 8086:8086
    volumes:
      - ./docker-compose/influxdb/data:/var/lib/influxdb2
      - ./docker-compose/influxdb/config:/etc/influxdb2
